import { Component, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NgForm } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';

import { Products } from '../../../models/products';
import { productService } from '../../../services/product.service';

@Component({
  selector: 'app-addproduct',
  imports: [FormsModule, CommonModule],
  templateUrl: './addproduct.component.html',
  styleUrl: './addproduct.component.scss',
})
export class AddproductComponent implements OnInit, OnChanges {
  // Define model properties for product inputs
  id: number = 0;
  productName: string = '';
  productFee: number = 0.0;
  productDescription: string = '';
  image: string = '';

  // Array to hold all the products
  productList: Products[] = [];
  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private productService: productService
  ) {}

  ngOnInit(): void {
    const productId = this.route.snapshot.paramMap.get('id');
    if (productId) {
      this.productService.getProductById(+productId).subscribe({
        next: (product) => {
          this.id = product.id;
          this.productName = product.name;
          this.productDescription = product.description;
          this.productFee = product.price;
          this.image = product.image;
        },
        error: (error) => {
          console.error('Error fetching product details:', error);
          alert('Failed to fetch product details.');
        },
      });
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    const productId = this.route.snapshot.paramMap.get('id');
    if (productId) {
      this.productService.getProductById(+productId).subscribe({
        next: (product) => {
          this.id = product.id;
          this.productName = product.name;
          this.productDescription = product.description;
          this.productFee = product.price;
          this.image = product.image;
        },
        error: (error) => {
          console.error('Error fetching product details:', error);
          alert('Failed to fetch product details.');
        },
      });
    }
  }

  createProduct(productForm: NgForm): void {
    if (productForm.valid) {
      // Create a new Product instance
      const newProduct: Products = {
        id: 0, // ID will be generated by the backend or API
        name: this.productName,
        description: this.productDescription,
        price: this.productFee,
        image: this.image || 'default-image.jpg', // Fallback to default image if not provided
      };

      // Call the productService to add the new product
      this.productService.addProduct(newProduct).subscribe({
        next: (response) => {
          console.log('Product Created:', response);
          alert('Product successfully created!');
          this.goBack();
        },
        error: (error) => {
          console.error('Error creating product:', error);
          alert('Failed to create product. Please try again.');
        },
      });
    } else {
      alert('Please fill in all the fields correctly!');
    }
  }

  goBack() {
    this.router.navigate(['/products']);
  }
}
